// AUTO-GENERATED grammar articles for all departments & regions.
// Used by article() in fr.ts for natural French copy ("dans les Vosges",
// "dans la Marne", "en Occitanie"). Do not hand-edit; regenerate from
// src/seo/data/geography-national.json if the dataset changes.
export interface Article { dans: string; de: string }

export const DEPT_ARTICLE_FULL: Record<string, Article> = {
  "Ain": { dans: "dans l'Ain", de: "de l'Ain" },
  "Aisne": { dans: "dans l'Aisne", de: "de l'Aisne" },
  "Allier": { dans: "dans l'Allier", de: "de l'Allier" },
  "Alpes-Maritimes": { dans: "dans les Alpes-Maritimes", de: "des Alpes-Maritimes" },
  "Alpes-de-Haute-Provence": { dans: "dans les Alpes-de-Haute-Provence", de: "des Alpes-de-Haute-Provence" },
  "Ardennes": { dans: "dans les Ardennes", de: "des Ardennes" },
  "Ardèche": { dans: "dans l'Ardèche", de: "de l'Ardèche" },
  "Ariège": { dans: "dans l'Ariège", de: "de l'Ariège" },
  "Aube": { dans: "dans l'Aube", de: "de l'Aube" },
  "Aude": { dans: "dans l'Aude", de: "de l'Aude" },
  "Aveyron": { dans: "dans l'Aveyron", de: "de l'Aveyron" },
  "Bas-Rhin": { dans: "dans le Bas-Rhin", de: "du Bas-Rhin" },
  "Bouches-du-Rhône": { dans: "dans les Bouches-du-Rhône", de: "des Bouches-du-Rhône" },
  "Calvados": { dans: "dans le Calvados", de: "du Calvados" },
  "Cantal": { dans: "dans le Cantal", de: "du Cantal" },
  "Charente": { dans: "dans la Charente", de: "de la Charente" },
  "Charente-Maritime": { dans: "dans la Charente-Maritime", de: "de la Charente-Maritime" },
  "Cher": { dans: "dans le Cher", de: "du Cher" },
  "Corrèze": { dans: "dans la Corrèze", de: "de la Corrèze" },
  "Corse-du-Sud": { dans: "en Corse-du-Sud", de: "de Corse-du-Sud" },
  "Creuse": { dans: "dans la Creuse", de: "de la Creuse" },
  "Côte-d'Or": { dans: "dans la Côte-d'Or", de: "de la Côte-d'Or" },
  "Côtes-d'Armor": { dans: "dans les Côtes-d'Armor", de: "des Côtes-d'Armor" },
  "Deux-Sèvres": { dans: "dans les Deux-Sèvres", de: "des Deux-Sèvres" },
  "Dordogne": { dans: "dans la Dordogne", de: "de la Dordogne" },
  "Doubs": { dans: "dans le Doubs", de: "du Doubs" },
  "Drôme": { dans: "dans la Drôme", de: "de la Drôme" },
  "Essonne": { dans: "dans l'Essonne", de: "de l'Essonne" },
  "Eure": { dans: "dans l'Eure", de: "de l'Eure" },
  "Eure-et-Loir": { dans: "dans l'Eure-et-Loir", de: "de l'Eure-et-Loir" },
  "Finistère": { dans: "dans le Finistère", de: "du Finistère" },
  "Gard": { dans: "dans le Gard", de: "du Gard" },
  "Gers": { dans: "dans le Gers", de: "du Gers" },
  "Gironde": { dans: "dans la Gironde", de: "de la Gironde" },
  "Guadeloupe": { dans: "en Guadeloupe", de: "de Guadeloupe" },
  "Guyane": { dans: "en Guyane", de: "de Guyane" },
  "Haut-Rhin": { dans: "dans le Haut-Rhin", de: "du Haut-Rhin" },
  "Haute-Corse": { dans: "en Haute-Corse", de: "de Haute-Corse" },
  "Haute-Garonne": { dans: "dans la Haute-Garonne", de: "de la Haute-Garonne" },
  "Haute-Loire": { dans: "dans la Haute-Loire", de: "de la Haute-Loire" },
  "Haute-Marne": { dans: "dans la Haute-Marne", de: "de la Haute-Marne" },
  "Haute-Savoie": { dans: "dans la Haute-Savoie", de: "de la Haute-Savoie" },
  "Haute-Saône": { dans: "dans la Haute-Saône", de: "de la Haute-Saône" },
  "Haute-Vienne": { dans: "dans la Haute-Vienne", de: "de la Haute-Vienne" },
  "Hautes-Alpes": { dans: "dans les Hautes-Alpes", de: "des Hautes-Alpes" },
  "Hautes-Pyrénées": { dans: "dans les Hautes-Pyrénées", de: "des Hautes-Pyrénées" },
  "Hauts-de-Seine": { dans: "dans les Hauts-de-Seine", de: "des Hauts-de-Seine" },
  "Hérault": { dans: "dans la Hérault", de: "de la Hérault" },
  "Ille-et-Vilaine": { dans: "dans l'Ille-et-Vilaine", de: "de l'Ille-et-Vilaine" },
  "Indre": { dans: "dans l'Indre", de: "de l'Indre" },
  "Indre-et-Loire": { dans: "dans l'Indre-et-Loire", de: "de l'Indre-et-Loire" },
  "Isère": { dans: "dans l'Isère", de: "de l'Isère" },
  "Jura": { dans: "dans le Jura", de: "du Jura" },
  "La Réunion": { dans: "à La Réunion", de: "de La Réunion" },
  "Landes": { dans: "dans les Landes", de: "des Landes" },
  "Loir-et-Cher": { dans: "dans le Loir-et-Cher", de: "du Loir-et-Cher" },
  "Loire": { dans: "dans la Loire", de: "de la Loire" },
  "Loire-Atlantique": { dans: "dans la Loire-Atlantique", de: "de la Loire-Atlantique" },
  "Loiret": { dans: "dans le Loiret", de: "du Loiret" },
  "Lot": { dans: "dans le Lot", de: "du Lot" },
  "Lot-et-Garonne": { dans: "dans le Lot-et-Garonne", de: "du Lot-et-Garonne" },
  "Lozère": { dans: "dans la Lozère", de: "de la Lozère" },
  "Maine-et-Loire": { dans: "dans le Maine-et-Loire", de: "du Maine-et-Loire" },
  "Manche": { dans: "dans la Manche", de: "de la Manche" },
  "Marne": { dans: "dans la Marne", de: "de la Marne" },
  "Martinique": { dans: "en Martinique", de: "de Martinique" },
  "Mayenne": { dans: "dans la Mayenne", de: "de la Mayenne" },
  "Mayotte": { dans: "à Mayotte", de: "de Mayotte" },
  "Meurthe-et-Moselle": { dans: "dans la Meurthe-et-Moselle", de: "de la Meurthe-et-Moselle" },
  "Meuse": { dans: "dans la Meuse", de: "de la Meuse" },
  "Morbihan": { dans: "dans le Morbihan", de: "du Morbihan" },
  "Moselle": { dans: "dans la Moselle", de: "de la Moselle" },
  "Nièvre": { dans: "dans la Nièvre", de: "de la Nièvre" },
  "Nord": { dans: "dans le Nord", de: "du Nord" },
  "Oise": { dans: "dans l'Oise", de: "de l'Oise" },
  "Orne": { dans: "dans l'Orne", de: "de l'Orne" },
  "Paris": { dans: "à Paris", de: "de Paris" },
  "Pas-de-Calais": { dans: "dans le Pas-de-Calais", de: "du Pas-de-Calais" },
  "Puy-de-Dôme": { dans: "dans le Puy-de-Dôme", de: "du Puy-de-Dôme" },
  "Pyrénées-Atlantiques": { dans: "dans les Pyrénées-Atlantiques", de: "des Pyrénées-Atlantiques" },
  "Pyrénées-Orientales": { dans: "dans les Pyrénées-Orientales", de: "des Pyrénées-Orientales" },
  "Rhône": { dans: "dans le Rhône", de: "du Rhône" },
  "Sarthe": { dans: "dans la Sarthe", de: "de la Sarthe" },
  "Savoie": { dans: "dans la Savoie", de: "de la Savoie" },
  "Saône-et-Loire": { dans: "dans la Saône-et-Loire", de: "de la Saône-et-Loire" },
  "Seine-Maritime": { dans: "dans la Seine-Maritime", de: "de la Seine-Maritime" },
  "Seine-Saint-Denis": { dans: "dans la Seine-Saint-Denis", de: "de la Seine-Saint-Denis" },
  "Seine-et-Marne": { dans: "dans la Seine-et-Marne", de: "de la Seine-et-Marne" },
  "Somme": { dans: "dans la Somme", de: "de la Somme" },
  "Tarn": { dans: "dans le Tarn", de: "du Tarn" },
  "Tarn-et-Garonne": { dans: "dans le Tarn-et-Garonne", de: "du Tarn-et-Garonne" },
  "Territoire de Belfort": { dans: "dans le Territoire de Belfort", de: "du Territoire de Belfort" },
  "Val-d'Oise": { dans: "dans le Val-d'Oise", de: "du Val-d'Oise" },
  "Val-de-Marne": { dans: "dans le Val-de-Marne", de: "du Val-de-Marne" },
  "Var": { dans: "dans le Var", de: "du Var" },
  "Vaucluse": { dans: "dans le Vaucluse", de: "du Vaucluse" },
  "Vendée": { dans: "dans la Vendée", de: "de la Vendée" },
  "Vienne": { dans: "dans la Vienne", de: "de la Vienne" },
  "Vosges": { dans: "dans les Vosges", de: "des Vosges" },
  "Yonne": { dans: "dans l'Yonne", de: "de l'Yonne" },
  "Yvelines": { dans: "dans les Yvelines", de: "des Yvelines" },
};

export const REGION_ARTICLE: Record<string, Article> = {
  "Auvergne-Rhône-Alpes": { dans: "en Auvergne-Rhône-Alpes", de: "d'Auvergne-Rhône-Alpes" },
  "Bourgogne-Franche-Comté": { dans: "en Bourgogne-Franche-Comté", de: "de Bourgogne-Franche-Comté" },
  "Bretagne": { dans: "en Bretagne", de: "de Bretagne" },
  "Centre-Val de Loire": { dans: "dans le Centre-Val de Loire", de: "du Centre-Val de Loire" },
  "Corse": { dans: "en Corse", de: "de Corse" },
  "Grand Est": { dans: "dans le Grand Est", de: "du Grand Est" },
  "Guadeloupe": { dans: "en Guadeloupe", de: "de Guadeloupe" },
  "Guyane": { dans: "en Guyane", de: "de Guyane" },
  "Hauts-de-France": { dans: "dans les Hauts-de-France", de: "des Hauts-de-France" },
  "La Réunion": { dans: "à La Réunion", de: "de La Réunion" },
  "Martinique": { dans: "en Martinique", de: "de Martinique" },
  "Mayotte": { dans: "à Mayotte", de: "de Mayotte" },
  "Normandie": { dans: "en Normandie", de: "de Normandie" },
  "Nouvelle-Aquitaine": { dans: "en Nouvelle-Aquitaine", de: "de Nouvelle-Aquitaine" },
  "Occitanie": { dans: "en Occitanie", de: "d'Occitanie" },
  "Pays de la Loire": { dans: "dans les Pays de la Loire", de: "des Pays de la Loire" },
  "Provence-Alpes-Côte d'Azur": { dans: "en Provence-Alpes-Côte d'Azur", de: "de Provence-Alpes-Côte d'Azur" },
  "Île-de-France": { dans: "en Île-de-France", de: "d'Île-de-France" },
};
